#!/usr/bin/env node
// Copyright 2026 Danish A. Licensed under Apache-2.0.
// AeroFyta CLI — Run the autonomous payment agent from command line

import { readFileSync, writeFileSync, existsSync, appendFileSync, unlinkSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';
import { execSync } from 'node:child_process';
import { handleWalletCommand } from './wallet-commands.js';
import { handlePaymentCommand } from './payment-commands.js';
import { handleSecurityCommand } from './security-commands.js';
import { handleDataCommand } from './data-commands.js';
import { handleAgentCommand } from './agent-commands.js';
import { handleAnalyticsCommand } from './analytics-commands.js';
import { handleDefiCommand } from './defi-commands.js';
import { handleMcpCommand } from './mcp-commands.js';
import { handleSystemCommand } from './system-commands.js';

// ── ANSI helpers (zero deps) ────────────────────────────────────────
const c = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  green: '\x1b[32m',
  cyan: '\x1b[36m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  magenta: '\x1b[35m',
  blue: '\x1b[34m',
  white: '\x1b[97m',
  bgCyan: '\x1b[46m',
  bgBlue: '\x1b[44m',
};

const ok = `${c.green}\u2705${c.reset}`;
const fail = `${c.red}\u274C${c.reset}`;
const warn = `${c.yellow}\u26A0${c.reset}`;
const infoIcon = `${c.blue}\u2139\uFE0F${c.reset}`;

function banner(): void {
  console.log(`
${c.cyan}${c.bold}    _                  _____       _
   / \\   ___ _ __ ___ |  ___|_   _| |_ __ _
  / _ \\ / _ \\ '__/ _ \\| |_  | | | | __/ _\` |
 / ___ \\  __/ | | (_) |  _| | |_| | || (_| |
/_/   \\_\\___|_|  \\___/|_|    \\__, |\\__\\__,_|
                             |___/
${c.reset}${c.dim}  AI Remittance Agent \u2022 USD\u2192MXN \u2022 Arbitrum + Base + Bitso${c.reset}
`);
}

function heading(text: string): void {
  console.log(`\n${c.bold}${c.cyan}\u2500\u2500 ${text} ${'─'.repeat(Math.max(0, 52 - text.length))}${c.reset}\n`);
}

function row(label: string, value: string): void {
  console.log(`  ${c.dim}${label.padEnd(20)}${c.reset} ${value}`);
}

// ── Read package.json ───────────────────────────────────────────────
function getPkg(): { version: string; description: string; homepage: string } {
  try {
    const dir = dirname(fileURLToPath(import.meta.url));
    const pkgPath = join(dir, '..', '..', 'package.json');
    return JSON.parse(readFileSync(pkgPath, 'utf-8'));
  } catch {
    return { version: '1.0.0', description: '', homepage: '' };
  }
}

// ── Server URL helper ───────────────────────────────────────────────
function serverUrl(path: string): string {
  const port = process.env['PORT'] || '3001';
  return `http://localhost:${port}${path}`;
}

// ── .env helpers ────────────────────────────────────────────────────
function envPath(): string {
  return join(process.cwd(), '.env');
}

function parseEnv(filepath: string): Map<string, string> {
  const map = new Map<string, string>();
  if (!existsSync(filepath)) return map;
  const lines = readFileSync(filepath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    map.set(key, val);
  }
  return map;
}

const SECRET_PATTERNS = ['secret', 'key', 'seed', 'token', 'password', 'mnemonic', 'private'];

function maskValue(key: string, value: string): string {
  const lk = key.toLowerCase();
  const isSecret = SECRET_PATTERNS.some(p => lk.includes(p));
  if (!isSecret) return value;
  if (value.length <= 8) return '****';
  return `${value.slice(0, 4)}${'*'.repeat(Math.min(value.length - 4, 20))}`;
}

// ── Commands ────────────────────────────────────────────────────────

function generateEnvContent(): string {
  const seedHex = randomBytes(32).toString('hex');
  const wordlist = [
    'alpha', 'bravo', 'chain', 'delta', 'echo', 'foxtrot', 'gamma', 'hotel',
    'india', 'juliet', 'kilo', 'lima', 'metro', 'nova', 'oscar', 'papa',
    'quest', 'rover', 'sigma', 'tango', 'ultra', 'victor', 'whiskey', 'x-ray',
    'yankee', 'zulu', 'anchor', 'beacon', 'cipher', 'drift', 'ember', 'flash',
  ];
  const mnemonic = Array.from({ length: 12 }, () => {
    const idx = randomBytes(1)[0]! % wordlist.length;
    return wordlist[idx];
  }).join(' ');

  return `# AeroFyta Agent — Generated by CLI (${new Date().toISOString()})
# See .env.example for all options

# ── WDK Configuration ───────────────────────────────────
WDK_SEED=${mnemonic}
WDK_SEED_HEX=${seedHex}

# ── AI / LLM ────────────────────────────────────────────
# GROQ_API_KEY=gsk_your_key_here

# ── Server ───────────────────────────────────────────────
PORT=3001
HOST=0.0.0.0

# ── Agent Modes ──────────────────────────────────────────
DEMO_MODE=true
AUTONOMOUS_MODE=true

# ── Telegram Bot (optional) ─────────────────────────────
# TELEGRAM_BOT_TOKEN=your_bot_token_here

# ── Feature Flags ────────────────────────────────────────
ENABLE_ESCROW=true
ENABLE_DCA=true
ENABLE_BRIDGE=false
ENABLE_STREAMING=false

# ── Risk Engine ──────────────────────────────────────────
MAX_TIP_AMOUNT=100
DAILY_TIP_LIMIT=500
MAX_SINGLE_TIP_PCT=25
`;
}

function cmdInit(): void {
  heading('Initialize Environment');
  const ep = envPath();
  if (existsSync(ep)) {
    console.log(`  ${warn}  .env already exists at ${c.dim}${ep}${c.reset}`);
    console.log(`  ${c.dim}Delete it first if you want to regenerate.${c.reset}\n`);
    return;
  }

  writeFileSync(ep, generateEnvContent(), 'utf-8');
  console.log(`  ${ok} Created ${c.cyan}.env${c.reset} at ${c.dim}${ep}${c.reset}`);
  console.log(`  ${ok} Generated random seed phrase (12 words)`);
  console.log(`  ${ok} Generated random seed hex (32 bytes)`);
  console.log(`\n  ${c.yellow}Next steps:${c.reset}`);
  console.log(`  1. ${c.dim}Get a free Groq key:${c.reset} ${c.cyan}https://console.groq.com${c.reset}`);
  console.log(`  2. ${c.dim}Add it to .env:${c.reset}     ${c.cyan}GROQ_API_KEY=gsk_...${c.reset}`);
  console.log(`  3. ${c.dim}Start the agent:${c.reset}    ${c.cyan}npm run dev${c.reset}\n`);
}

async function cmdStart(): Promise<void> {
  heading('Start Agent');
  console.log(`  ${infoIcon} To start the AeroFyta agent server, run:\n`);
  console.log(`    ${c.cyan}cd agent && npm run dev${c.reset}        ${c.dim}# development mode${c.reset}`);
  console.log(`    ${c.cyan}cd agent && npm start${c.reset}          ${c.dim}# production mode${c.reset}`);
  console.log(`    ${c.cyan}docker compose up${c.reset}              ${c.dim}# via Docker${c.reset}`);
  console.log();
  try {
    const res = await fetch(serverUrl('/api/agent/status'), { signal: AbortSignal.timeout(2000) });
    if (res.ok) {
      console.log(`  ${warn}  Agent is ${c.green}already running${c.reset} on port ${process.env['PORT'] || '3001'}`);
    }
  } catch {
    console.log(`  ${c.dim}Agent is not currently running.${c.reset}`);
  }
  console.log();
}

async function cmdStop(): Promise<void> {
  heading('Stop Agent');
  try {
    const res = await fetch(serverUrl('/api/agent/stop'), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      signal: AbortSignal.timeout(5000),
    });
    if (res.ok) {
      console.log(`  ${ok} Agent stop signal sent successfully.`);
    } else {
      console.log(`  ${fail} Agent returned HTTP ${res.status}: ${await res.text()}`);
    }
  } catch {
    console.log(`  ${fail} Agent is ${c.red}not running${c.reset} (could not reach server).`);
    console.log(`  ${c.dim}Nothing to stop.${c.reset}`);
  }
  console.log();
}

async function cmdRestart(): Promise<void> {
  heading('Restart Agent');
  try {
    const res = await fetch(serverUrl('/api/agent/restart'), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      signal: AbortSignal.timeout(5000),
    });
    if (res.ok) {
      console.log(`  ${ok} Agent restart signal sent successfully.`);
      console.log(`  ${c.dim}The agent will restart momentarily.${c.reset}`);
    } else {
      console.log(`  ${fail} Agent returned HTTP ${res.status}: ${await res.text()}`);
    }
  } catch {
    console.log(`  ${fail} Agent is ${c.red}not running${c.reset} (could not reach server).`);
    console.log(`  ${c.dim}Start it first with:${c.reset} ${c.cyan}npm run dev${c.reset}`);
  }
  console.log();
}

function cmdConfigSet(key: string | undefined, value: string | undefined): void {
  heading('Config Set');
  if (!key || value === undefined) {
    console.log(`  ${fail} Usage: ${c.cyan}aerofyta config set <KEY> <VALUE>${c.reset}`);
    console.log(`  ${c.dim}Example: aerofyta config set PORT 3002${c.reset}\n`);
    return;
  }

  const ep = envPath();
  const upperKey = key.toUpperCase();

  if (!existsSync(ep)) {
    writeFileSync(ep, `${upperKey}=${value}\n`, 'utf-8');
    console.log(`  ${ok} Created .env and set ${c.cyan}${upperKey}${c.reset} = ${maskValue(upperKey, value)}\n`);
    return;
  }

  const lines = readFileSync(ep, 'utf-8').split('\n');
  let found = false;
  const updated = lines.map(line => {
    const trimmed = line.trim();
    if (trimmed.startsWith('#') || !trimmed) return line;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) return line;
    const lineKey = trimmed.slice(0, eqIdx).trim();
    if (lineKey === upperKey) {
      found = true;
      return `${upperKey}=${value}`;
    }
    return line;
  });

  if (found) {
    writeFileSync(ep, updated.join('\n'), 'utf-8');
    console.log(`  ${ok} Updated ${c.cyan}${upperKey}${c.reset} = ${maskValue(upperKey, value)}`);
  } else {
    appendFileSync(ep, `\n${upperKey}=${value}\n`, 'utf-8');
    console.log(`  ${ok} Added ${c.cyan}${upperKey}${c.reset} = ${maskValue(upperKey, value)}`);
  }
  console.log();
}

function cmdConfigGet(key: string | undefined): void {
  heading('Config Get');
  if (!key) {
    console.log(`  ${fail} Usage: ${c.cyan}aerofyta config get <KEY>${c.reset}\n`);
    return;
  }

  const ep = envPath();
  if (!existsSync(ep)) {
    console.log(`  ${fail} No .env file found. Run ${c.cyan}aerofyta init${c.reset} first.\n`);
    return;
  }

  const upperKey = key.toUpperCase();
  const env = parseEnv(ep);
  const val = env.get(upperKey);

  if (val !== undefined) {
    console.log(`  ${c.cyan}${upperKey}${c.reset} = ${maskValue(upperKey, val)}`);
  } else {
    console.log(`  ${fail} Key ${c.cyan}${upperKey}${c.reset} not found in .env`);
  }
  console.log();
}

function cmdConfigList(): void {
  heading('Config List');
  const ep = envPath();
  if (!existsSync(ep)) {
    console.log(`  ${fail} No .env file found. Run ${c.cyan}aerofyta init${c.reset} first.\n`);
    return;
  }

  const env = parseEnv(ep);
  if (env.size === 0) {
    console.log(`  ${c.dim}No variables set in .env${c.reset}\n`);
    return;
  }

  for (const [key, val] of env) {
    const display = maskValue(key, val);
    console.log(`  ${c.cyan}${key.padEnd(24)}${c.reset} ${display}`);
  }
  console.log(`\n  ${c.dim}${env.size} variable(s) loaded from ${ep}${c.reset}\n`);
}

function cmdConfigReset(): void {
  heading('Config Reset');
  const ep = envPath();
  if (existsSync(ep)) {
    try { unlinkSync(ep); } catch { /* ignore */ }
    console.log(`  ${ok} Removed existing .env`);
  }
  cmdInit();
}

function cmdVersion(): void {
  const pkg = getPkg();
  console.log(`  ${c.bold}${c.cyan}AeroFyta${c.reset} v${c.bold}${pkg.version}${c.reset}`);
  console.log(`  ${c.dim}Autonomous Multi-Chain Payment Agent${c.reset}`);
  console.log(`  ${c.dim}Powered by Tether WDK${c.reset}`);
  console.log();
  row('Version', `${c.green}${pkg.version}${c.reset}`);
  row('Node.js', process.version);
  row('Platform', `${process.platform} ${process.arch}`);
  row('License', 'Apache-2.0');
  console.log();
}

async function cmdUpdate(): Promise<void> {
  heading('Update AeroFyta');
  console.log(`  ${infoIcon} Checking for updates...\n`);
  try {
    execSync('npm update @xzashr/aerofyta', { stdio: 'inherit', cwd: process.cwd() });
    console.log(`\n  ${ok} Update complete.`);
  } catch {
    console.log(`\n  ${fail} Update failed. Try manually: ${c.cyan}npm update @xzashr/aerofyta${c.reset}`);
  }
  console.log();
}

async function cmdDoctor(): Promise<void> {
  heading('Doctor \u2014 System Health Check');
  let issues = 0;

  // 1. Node.js version >= 22
  const nodeVer = process.versions.node;
  const major = parseInt(nodeVer.split('.')[0]!, 10);
  if (major >= 22) {
    console.log(`  ${ok} Node.js ${c.green}v${nodeVer}${c.reset} (>= 22 required)`);
  } else {
    console.log(`  ${fail} Node.js ${c.red}v${nodeVer}${c.reset} \u2014 version 22+ required`);
    issues++;
  }

  // 2. .env exists and has critical keys
  const ep = envPath();
  if (existsSync(ep)) {
    const env = parseEnv(ep);
    console.log(`  ${ok} .env file found (${c.green}${env.size} vars${c.reset})`);

    if (env.has('WDK_SEED') || env.has('WDK_SEED_HEX')) {
      console.log(`  ${ok} WDK seed configured`);
    } else {
      console.log(`  ${warn}  WDK seed ${c.yellow}not set${c.reset} in .env`);
      issues++;
    }

    if (env.has('GROQ_API_KEY')) {
      console.log(`  ${ok} GROQ_API_KEY configured`);
    } else {
      console.log(`  ${warn}  GROQ_API_KEY ${c.yellow}not set${c.reset} \u2014 LLM features will be limited`);
      issues++;
    }
  } else {
    console.log(`  ${fail} .env file ${c.red}not found${c.reset} \u2014 run ${c.cyan}aerofyta init${c.reset}`);
    issues++;
  }

  // 3. .seed file (optional)
  const seedPath = join(process.cwd(), '.seed');
  if (existsSync(seedPath)) {
    console.log(`  ${ok} .seed file found`);
  } else {
    console.log(`  ${c.dim}  \u2500${c.reset} .seed file not found ${c.dim}(optional, .env seed used instead)${c.reset}`);
  }

  // 4. Check if server is running
  try {
    const res = await fetch(serverUrl('/api/agent/status'), { signal: AbortSignal.timeout(2000) });
    if (res.ok) {
      console.log(`  ${ok} Agent server is ${c.green}running${c.reset} on port ${process.env['PORT'] || '3001'}`);
    } else {
      console.log(`  ${warn}  Agent server returned HTTP ${res.status}`);
      issues++;
    }
  } catch {
    console.log(`  ${warn}  Agent server is ${c.yellow}not running${c.reset}`);
  }

  // 5. Check WDK packages
  const wdkPackages = [
    '@tetherto/wdk',
    '@tetherto/wdk-wallet-evm',
    '@tetherto/wdk-wallet-ton',
  ];
  const nodeModules = join(process.cwd(), 'node_modules');
  for (const pkg of wdkPackages) {
    const pkgDir = join(nodeModules, ...pkg.split('/'));
    if (existsSync(pkgDir)) {
      console.log(`  ${ok} ${c.dim}${pkg}${c.reset} installed`);
    } else {
      console.log(`  ${fail} ${c.red}${pkg}${c.reset} not installed`);
      issues++;
    }
  }

  // 6. Check package.json exists
  const pkgPath = join(process.cwd(), 'package.json');
  if (existsSync(pkgPath)) {
    console.log(`  ${ok} package.json found`);
  } else {
    console.log(`  ${fail} package.json ${c.red}not found${c.reset}`);
    issues++;
  }

  // Summary
  console.log();
  if (issues === 0) {
    console.log(`  ${ok} ${c.green}${c.bold}All checks passed!${c.reset} AeroFyta is ready.\n`);
  } else {
    console.log(`  ${warn}  ${c.yellow}${issues} issue(s) found.${c.reset} Fix them above and re-run ${c.cyan}aerofyta doctor${c.reset}.\n`);
  }
}

function cmdHelp(): void {
  const pkg = getPkg();
  console.log(`  ${c.bold}AeroFyta v${pkg.version}${c.reset} ${c.dim}\u2014 Autonomous Payment Agent${c.reset}\n`);
  console.log(`  ${c.bold}Usage:${c.reset} ${c.cyan}npx @xzashr/aerofyta${c.reset} ${c.yellow}<command>${c.reset} [options]\n`);

  // ── Getting Started ──
  console.log(`  ${c.bold}${c.green}Getting Started${c.reset}`);
  const startCmds: Array<[string, string]> = [
    ['init', 'Create .env with defaults, random seed, and all config options'],
    ['start', 'Show instructions to start the agent server'],
    ['stop', 'Stop the running agent server'],
    ['restart', 'Restart the running agent server'],
    ['status', 'Check if agent server is running'],
    ['doctor', 'Run system health checks (Node, .env, WDK, server)'],
  ];
  for (const [cmd, desc] of startCmds) {
    console.log(`    ${c.cyan}${cmd.padEnd(28)}${c.reset}${desc}`);
  }

  // ── Configuration ──
  console.log(`\n  ${c.bold}${c.green}Configuration${c.reset}`);
  const configCmds: Array<[string, string]> = [
    ['config set <KEY> <VALUE>', 'Set a config value in .env'],
    ['config get <KEY>', 'Read a config value from .env'],
    ['config list', 'Show all .env variables (secrets masked)'],
    ['config reset', 'Reset .env to defaults with new seed'],
  ];
  for (const [cmd, desc] of configCmds) {
    console.log(`    ${c.cyan}${cmd.padEnd(28)}${c.reset}${desc}`);
  }

  // ── Tipping & Payments ──
  console.log(`\n  ${c.bold}${c.green}Tipping & Payments${c.reset}`);
  const tipCmds: Array<[string, string]> = [
    ['tip <addr> <amount>', 'Send a USDT tip to an address'],
    ['tip history', 'Show recent tip history'],
    ['escrow create', 'Create a smart escrow'],
    ['escrow list', 'List all escrows'],
    ['escrow claim <id>', 'Claim an escrow'],
    ['escrow refund <id>', 'Refund an escrow'],
    ['split create', 'Create a split-tip group'],
    ['split execute <id>', 'Execute a pending split'],
    ['dca create', 'Create a DCA (dollar-cost-average) plan'],
    ['dca list', 'List DCA plans'],
    ['dca pause <id>', 'Pause a DCA plan'],
    ['dca resume <id>', 'Resume a DCA plan'],
    ['stream start', 'Start a payment stream'],
    ['stream stop <id>', 'Stop a payment stream'],
    ['subscribe create', 'Create a subscription'],
    ['subscribe list', 'List subscriptions'],
    ['x402 list', 'List x402 paywalls'],
    ['x402 stats', 'Show x402 statistics'],
  ];
  for (const [cmd, desc] of tipCmds) {
    console.log(`    ${c.cyan}${cmd.padEnd(28)}${c.reset}${desc}`);
  }

  // ── Wallet ──
  console.log(`\n  ${c.bold}${c.green}Wallet${c.reset}`);
  const walletCmds: Array<[string, string]> = [
    ['wallet show', 'Show wallet addresses'],
    ['wallet balance', 'Show all wallet balances'],
    ['wallet fund', 'Fund a wallet from testnet faucet'],
    ['wallet export', 'Export wallet data'],
    ['wallet import', 'Import wallet data'],
    ['wallet history', 'Show transaction history'],
    ['wallet gasless-test', 'Test gasless transaction'],
    ['wallet signer-verify', 'Verify wallet signer'],
  ];
  for (const [cmd, desc] of walletCmds) {
    console.log(`    ${c.cyan}${cmd.padEnd(28)}${c.reset}${desc}`);
  }

  // ── Security & Risk ──
  console.log(`\n  ${c.bold}${c.green}Security & Risk${c.reset}`);
  const secCmds: Array<[string, string]> = [
    ['test', 'Run adversarial safety tests'],
    ['audit', 'View audit log'],
    ['policy', 'View or update policies'],
    ['anomaly', 'Anomaly detection status'],
    ['credit', 'Credit scoring info'],
  ];
  for (const [cmd, desc] of secCmds) {
    console.log(`    ${c.cyan}${cmd.padEnd(28)}${c.reset}${desc}`);
  }

  // ── Data & Discovery ──
  console.log(`\n  ${c.bold}${c.green}Data & Discovery${c.reset}`);
  const dataCmds: Array<[string, string]> = [
    ['creators', 'Discover and list creators'],
    ['reputation', 'View reputation scores'],
    ['youtube', 'YouTube creator lookup'],
    ['rss', 'RSS feed management'],
    ['webhooks', 'Webhook management'],
    ['notifications', 'Notification settings'],
  ];
  for (const [cmd, desc] of dataCmds) {
    console.log(`    ${c.cyan}${cmd.padEnd(28)}${c.reset}${desc}`);
  }

  // ── Agent ──
  console.log(`\n  ${c.bold}${c.green}Agent${c.reset}`);
  const agentCmds: Array<[string, string]> = [
    ['agent', 'Agent overview'],
    ['demo', 'Run interactive demo showcasing capabilities'],
    ['status', 'Check if agent server is running'],
    ['pulse', 'Show financial pulse metrics'],
    ['mood', 'Show current agent mood'],
    ['reason', 'Show recent reasoning traces'],
    ['ask', 'Ask the agent a question'],
    ['tool-use', 'Show recent tool usage'],
    ['logs', 'Show agent logs'],
  ];
  for (const [cmd, desc] of agentCmds) {
    console.log(`    ${c.cyan}${cmd.padEnd(28)}${c.reset}${desc}`);
  }

  // ── Analytics ──
  console.log(`\n  ${c.bold}${c.green}Analytics${c.reset}`);
  const analyticsCmds: Array<[string, string]> = [
    ['analytics overview', 'Analytics overview dashboard'],
    ['analytics tips', 'Tip analytics breakdown'],
    ['analytics creators', 'Top creators analytics'],
    ['analytics chains', 'Chain usage analytics'],
    ['analytics decisions', 'Decision history analytics'],
    ['analytics export', 'Export analytics data'],
  ];
  for (const [cmd, desc] of analyticsCmds) {
    console.log(`    ${c.cyan}${cmd.padEnd(28)}${c.reset}${desc}`);
  }

  // ── DeFi ──
  console.log(`\n  ${c.bold}${c.green}DeFi${c.reset}`);
  const defiCmds: Array<[string, string]> = [
    ['deploy', 'Deploy a smart contract'],
    ['proof', 'Generate a ZK proof'],
    ['yield', 'Show yield opportunities'],
    ['swap', 'Execute a token swap'],
    ['bridge', 'Bridge assets cross-chain'],
    ['lend', 'Lending protocol operations'],
  ];
  for (const [cmd, desc] of defiCmds) {
    console.log(`    ${c.cyan}${cmd.padEnd(28)}${c.reset}${desc}`);
  }

  // ── MCP / SDK / Plugin ──
  console.log(`\n  ${c.bold}${c.green}MCP / SDK / Plugin${c.reset}`);
  const mcpCmds: Array<[string, string]> = [
    ['mcp tools', 'List all 97+ MCP tools'],
    ['mcp status', 'Check MCP server status'],
    ['sdk presets', 'Show SDK presets'],
    ['sdk hooks list', 'Show SDK hook event types'],
    ['sdk adapters', 'Show chain adapters'],
    ['plugin status', 'Show registered service modules'],
  ];
  for (const [cmd, desc] of mcpCmds) {
    console.log(`    ${c.cyan}${cmd.padEnd(28)}${c.reset}${desc}`);
  }

  // ── System ──
  console.log(`\n  ${c.bold}${c.green}System${c.reset}`);
  const sysCmds: Array<[string, string]> = [
    ['info', 'Show features, WDK integrations, and package info'],
    ['docs', 'Show documentation links'],
    ['health', 'Detailed health check'],
    ['modules', 'List loaded modules'],
    ['architecture', 'Show system architecture'],
    ['persistence', 'Show persistence layer status'],
    ['auth', 'Show authentication status'],
    ['zk', 'Show zero-knowledge proof status'],
    ['benchmark', 'Run performance benchmarks'],
  ];
  for (const [cmd, desc] of sysCmds) {
    console.log(`    ${c.cyan}${cmd.padEnd(28)}${c.reset}${desc}`);
  }

  // ── Info & Maintenance ──
  console.log(`\n  ${c.bold}${c.green}Info & Maintenance${c.reset}`);
  const infoCmds: Array<[string, string]> = [
    ['version', 'Show version and runtime info'],
    ['update', 'Update AeroFyta to the latest version'],
    ['help', 'Show this help message'],
  ];
  for (const [cmd, desc] of infoCmds) {
    console.log(`    ${c.cyan}${cmd.padEnd(28)}${c.reset}${desc}`);
  }

  // ── API Endpoints (informational) ──
  console.log(`\n  ${c.bold}${c.green}API Endpoints${c.reset} ${c.dim}(when server is running on :3001)${c.reset}`);
  const apis: Array<[string, string]> = [
    ['GET  /api/agent/status', 'Agent status and mood'],
    ['POST /api/tip', 'Send a tip'],
    ['POST /api/tip/split', 'Split a tip among recipients'],
    ['GET  /api/wallets', 'List connected wallets'],
    ['GET  /api/wallets/balances', 'Get all wallet balances'],
    ['POST /api/escrow/create', 'Create a smart escrow'],
    ['GET  /api/escrow/list', 'List escrows'],
    ['POST /api/dca/create', 'Create a DCA plan'],
    ['GET  /api/dca/list', 'List DCA plans'],
    ['POST /api/bridge/quote', 'Get a cross-chain bridge quote'],
    ['POST /api/swap/quote', 'Get a token swap quote'],
    ['GET  /api/analytics/summary', 'Tip analytics summary'],
    ['GET  /api/reputation/:addr', 'Reputation score for address'],
    ['POST /api/chat', 'Chat with the AI agent'],
    ['GET  /api/orchestrator/status', 'Multi-agent orchestrator status'],
    ['GET  /api/streaming/active', 'Active payment streams'],
    ['GET  /api/treasury/summary', 'Treasury summary'],
    ['GET  /api/memory/summary', 'Agent memory summary'],
    ['GET  /api/autonomy/status', 'Autonomous loop status'],
    ['GET  /api/risk/dashboard', 'Risk engine dashboard'],
    ['GET  /api/health', 'Health check'],
    ['GET  /api/docs', 'OpenAPI documentation'],
  ];
  for (const [cmd, desc] of apis) {
    console.log(`    ${c.dim}${cmd.padEnd(32)}${c.reset}${desc}`);
  }

  // ── MCP Tools ──
  console.log(`\n  ${c.bold}${c.green}MCP Tools${c.reset} ${c.dim}(for AI integrations)${c.reset}`);
  const mcpTools: Array<[string, string]> = [
    ['send_tip', 'Send a tip via MCP'],
    ['get_balance', 'Get wallet balance via MCP'],
    ['get_agent_status', 'Agent status via MCP'],
    ['create_escrow', 'Create escrow via MCP'],
    ['analyze_creator', 'Analyze a content creator via MCP'],
    ['get_tip_history', 'Tip history via MCP'],
  ];
  for (const [cmd, desc] of mcpTools) {
    console.log(`    ${c.dim}${cmd.padEnd(28)}${c.reset}${desc}`);
  }

  console.log(`\n  ${c.bold}Examples:${c.reset}`);
  console.log(`    ${c.dim}$${c.reset} npx @xzashr/aerofyta init`);
  console.log(`    ${c.dim}$${c.reset} npx @xzashr/aerofyta doctor`);
  console.log(`    ${c.dim}$${c.reset} npx @xzashr/aerofyta config set GROQ_API_KEY gsk_abc123`);
  console.log(`    ${c.dim}$${c.reset} npx @xzashr/aerofyta config list`);
  console.log(`    ${c.dim}$${c.reset} npx @xzashr/aerofyta tip 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 2.50`);
  console.log(`    ${c.dim}$${c.reset} npx @xzashr/aerofyta status`);
  console.log(`    ${c.dim}$${c.reset} npx @xzashr/aerofyta demo\n`);
}

// ── Main ────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const command = args[0] || 'help';

banner();

switch (command) {
  // ── Agent commands ──
  case 'agent':
  case 'demo':
  case 'status':
  case 'pulse':
  case 'mood':
  case 'reason':
  case 'ask':
  case 'tool-use':
  case 'logs':
    await handleAgentCommand(command, args.slice(1));
    break;

  // ── Analytics commands ──
  case 'analytics':
    await handleAnalyticsCommand(args[1], args.slice(2));
    break;

  // ── DeFi commands ──
  case 'deploy':
  case 'proof':
  case 'yield':
  case 'swap':
  case 'bridge':
  case 'lend':
    await handleDefiCommand(command, args[1], args.slice(2));
    break;

  // ── MCP / SDK / Plugin commands ──
  case 'mcp':
  case 'sdk':
  case 'plugin':
    await handleMcpCommand(command, args[1], args.slice(2));
    break;

  // ── System commands ──
  case 'info':
  case 'docs':
  case 'health':
  case 'modules':
  case 'architecture':
  case 'persistence':
  case 'auth':
  case 'zk':
  case 'benchmark':
    await handleSystemCommand(command, args[1], args.slice(2));
    break;

  // ── Core commands ──
  case 'init':
    cmdInit();
    break;
  case 'start':
    await cmdStart();
    break;
  case 'stop':
    await cmdStop();
    break;
  case 'restart':
    await cmdRestart();
    break;
  case 'config': {
    const subCmd = args[1];
    switch (subCmd) {
      case 'set':
        cmdConfigSet(args[2], args.slice(3).join(' ') || undefined);
        break;
      case 'get':
        cmdConfigGet(args[2]);
        break;
      case 'list':
        cmdConfigList();
        break;
      case 'reset':
        cmdConfigReset();
        break;
      default:
        console.log(`  ${fail} Unknown config subcommand: ${c.red}${subCmd || '(none)'}${c.reset}`);
        console.log(`  ${c.dim}Available: set, get, list, reset${c.reset}\n`);
        break;
    }
    break;
  }
  case 'version':
  case '-v':
  case '--version':
    cmdVersion();
    break;
  case 'update':
    await cmdUpdate();
    break;
  case 'doctor':
    await cmdDoctor();
    break;
  case 'tip':
  case 'escrow':
  case 'split':
  case 'dca':
  case 'stream':
  case 'subscribe':
  case 'x402':
    await handlePaymentCommand(command, args[1], args.slice(2));
    break;
  case 'wallet':
    await handleWalletCommand(args[1], args.slice(2));
    break;
  case 'test':
  case 'audit':
  case 'policy':
  case 'anomaly':
  case 'credit':
    await handleSecurityCommand(command, args[1], args.slice(2));
    break;
  case 'creators':
  case 'reputation':
  case 'youtube':
  case 'rss':
  case 'webhooks':
  case 'notifications':
    await handleDataCommand(command, args[1], args.slice(2));
    break;
  case 'help':
  case '-h':
  case '--help':
  default:
    cmdHelp();
    break;
}
