// Copyright 2026 AeroFyta. Apache-2.0 license.

import type { TipHistoryEntry } from '../types/index.js';

/** Multi-format export service for transaction history */
export class ExportService {
  /** Export history as CSV */
  exportCSV(history: TipHistoryEntry[]): string {
    const headers = ['Date', 'Recipient', 'Amount', 'Token', 'Chain', 'Status', 'TxHash', 'Fee', 'Reasoning'];
    const rows = history.map((entry) => {
      const token = entry.token === 'usdt' ? 'USDT' : entry.chainId.startsWith('ethereum') ? 'ETH' : 'TON';
      const chain = entry.chainId.startsWith('ethereum') ? 'Ethereum Sepolia' : 'TON Testnet';
      return [
        entry.createdAt,
        entry.recipient,
        entry.amount,
        token,
        chain,
        entry.status,
        entry.txHash,
        entry.fee,
        entry.reasoning.replace(/"/g, '""'),
      ].map((v) => `"${v}"`).join(',');
    });
    return [headers.join(','), ...rows].join('\n');
  }

  /** Export history as pretty-printed JSON */
  exportJSON(history: TipHistoryEntry[]): string {
    const entries = history.map((entry) => ({
      id: entry.id,
      date: entry.createdAt,
      recipient: entry.recipient,
      amount: entry.amount,
      token: entry.token === 'usdt' ? 'USDT' : entry.chainId.startsWith('ethereum') ? 'ETH' : 'TON',
      chain: entry.chainId.startsWith('ethereum') ? 'Ethereum Sepolia' : 'TON Testnet',
      chainId: entry.chainId,
      status: entry.status,
      txHash: entry.txHash,
      fee: entry.fee,
      reasoning: entry.reasoning,
    }));
    return JSON.stringify({ exportedAt: new Date().toISOString(), totalEntries: entries.length, history: entries }, null, 2);
  }

  /** Export history as a Markdown table */
  exportMarkdown(history: TipHistoryEntry[]): string {
    const lines: string[] = [];
    lines.push('# AeroFyta Transaction History');
    lines.push('');
    lines.push(`Exported: ${new Date().toISOString()}`);
    lines.push(`Total transactions: ${history.length}`);
    lines.push('');
    lines.push('| Date | Recipient | Amount | Token | Chain | Status | Fee |');
    lines.push('|------|-----------|--------|-------|-------|--------|-----|');

    for (const entry of history) {
      const token = entry.token === 'usdt' ? 'USDT' : entry.chainId.startsWith('ethereum') ? 'ETH' : 'TON';
      const chain = entry.chainId.startsWith('ethereum') ? 'Ethereum Sepolia' : 'TON Testnet';
      const shortAddr = entry.recipient.length > 14
        ? `${entry.recipient.slice(0, 6)}...${entry.recipient.slice(-4)}`
        : entry.recipient;
      const date = entry.createdAt.replace('T', ' ').slice(0, 19);
      const status = entry.status === 'confirmed' ? 'OK' : 'FAIL';
      lines.push(`| ${date} | \`${shortAddr}\` | ${entry.amount} | ${token} | ${chain} | ${status} | ${entry.fee} |`);
    }

    lines.push('');
    lines.push('---');
    lines.push('*Generated by AeroFyta + Tether WDK*');
    return lines.join('\n');
  }

  /** Export a text summary report with aggregated stats */
  exportSummary(history: TipHistoryEntry[]): string {
    const confirmed = history.filter((h) => h.status === 'confirmed');
    const failed = history.filter((h) => h.status === 'failed');

    const totalVolume = confirmed.reduce((sum, h) => sum + parseFloat(h.amount || '0'), 0);
    const totalFees = confirmed.reduce((sum, h) => {
      const n = parseFloat(h.fee?.replace(/[^0-9.e-]/g, '') || '0');
      return sum + (isNaN(n) ? 0 : n);
    }, 0);
    const successRate = history.length > 0 ? ((confirmed.length / history.length) * 100).toFixed(1) : '0';

    // Chain breakdown
    const chainCounts: Record<string, number> = {};
    const chainVolumes: Record<string, number> = {};
    for (const h of confirmed) {
      const chain = h.chainId.startsWith('ethereum') ? 'Ethereum Sepolia' : 'TON Testnet';
      chainCounts[chain] = (chainCounts[chain] ?? 0) + 1;
      chainVolumes[chain] = (chainVolumes[chain] ?? 0) + parseFloat(h.amount || '0');
    }

    // Token breakdown
    const tokenCounts: Record<string, number> = {};
    for (const h of confirmed) {
      const token = h.token === 'usdt' ? 'USDT' : h.chainId.startsWith('ethereum') ? 'ETH' : 'TON';
      tokenCounts[token] = (tokenCounts[token] ?? 0) + 1;
    }

    // Date range
    const dates = history.map((h) => new Date(h.createdAt).getTime()).filter((t) => !isNaN(t));
    const earliest = dates.length > 0 ? new Date(Math.min(...dates)).toISOString().split('T')[0] : 'N/A';
    const latest = dates.length > 0 ? new Date(Math.max(...dates)).toISOString().split('T')[0] : 'N/A';

    // Unique recipients
    const uniqueRecipients = new Set(confirmed.map((h) => h.recipient.toLowerCase())).size;

    const lines: string[] = [];
    lines.push('========================================');
    lines.push('  AeroFyta Transaction Summary Report');
    lines.push('========================================');
    lines.push('');
    lines.push(`Report generated: ${new Date().toISOString()}`);
    lines.push(`Date range: ${earliest} to ${latest}`);
    lines.push('');
    lines.push('--- Overview ---');
    lines.push(`Total transactions:   ${history.length}`);
    lines.push(`Successful:           ${confirmed.length}`);
    lines.push(`Failed:               ${failed.length}`);
    lines.push(`Success rate:         ${successRate}%`);
    lines.push(`Total volume:         ${totalVolume.toFixed(6)}`);
    lines.push(`Total fees paid:      ${totalFees.toFixed(8)}`);
    lines.push(`Unique recipients:    ${uniqueRecipients}`);
    if (confirmed.length > 0) {
      lines.push(`Average tip size:     ${(totalVolume / confirmed.length).toFixed(6)}`);
    }
    lines.push('');
    lines.push('--- By Chain ---');
    for (const [chain, count] of Object.entries(chainCounts)) {
      lines.push(`  ${chain}: ${count} tips, volume ${(chainVolumes[chain] ?? 0).toFixed(6)}`);
    }
    lines.push('');
    lines.push('--- By Token ---');
    for (const [token, count] of Object.entries(tokenCounts)) {
      lines.push(`  ${token}: ${count} tips`);
    }
    lines.push('');
    lines.push('========================================');
    lines.push('  Powered by AeroFyta + Tether WDK');
    lines.push('========================================');
    return lines.join('\n');
  }
}
