// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Danish A.
// AeroFyta — Groth16 ZK-SNARK Verifier for CreditProof circuit.
//
// This is a template verifier contract. In production, the pairing
// check constants (vk_alpha, vk_beta, vk_gamma, vk_delta, IC) would
// be generated by `snarkjs zkey export solidityverifier`.
//
// The contract verifies on-chain that a prover knows a credit score
// exceeding a public threshold, without revealing the score itself.

pragma solidity ^0.8.24;

contract CreditProofVerifier {

    // ── Groth16 proof structure ─────────────────────────────────
    struct Proof {
        uint256[2] a;       // G1 point
        uint256[2][2] b;    // G2 point
        uint256[2] c;       // G1 point
    }

    // ── Verification key (populated by snarkjs export) ─────────
    // In a full deployment these would be immutable constants
    // derived from the trusted setup ceremony.

    uint256 constant SNARK_SCALAR_FIELD = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // ── Events ──────────────────────────────────────────────────
    event ProofVerified(
        address indexed verifier,
        uint256 threshold,
        uint256 commitment,
        bool valid
    );

    /**
     * @notice Verify a Groth16 proof that a credit score >= threshold.
     * @param a  Proof element A (G1 point)
     * @param b  Proof element B (G2 point)
     * @param c  Proof element C (G1 point)
     * @param input  Public signals: [threshold, commitment]
     * @return valid  True if the proof is valid
     *
     * @dev In the full version, this performs an elliptic curve
     * pairing check:
     *   e(A, B) == e(alpha, beta) * e(IC, gamma) * e(C, delta)
     *
     * The template below validates input formatting and field
     * membership. Replace with snarkjs-generated pairing logic
     * for production use.
     */
    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[2] memory input  // [threshold, commitment]
    ) public returns (bool valid) {
        // Validate that inputs are within the scalar field
        require(input[0] < SNARK_SCALAR_FIELD, "threshold out of field");
        require(input[1] < SNARK_SCALAR_FIELD, "commitment out of field");

        // Validate that proof points are non-zero
        require(a[0] != 0 || a[1] != 0, "proof.a is zero");
        require(c[0] != 0 || c[1] != 0, "proof.c is zero");

        // Validate that public inputs are meaningful
        require(input[0] > 0, "threshold must be positive");
        require(input[1] > 0, "commitment must be non-zero");

        // ── Pairing check placeholder ───────────────────────────
        // In production, snarkjs generates the full pairing check
        // using precompiled contracts at addresses 0x06, 0x07, 0x08.
        //
        // For the hackathon template, we validate structural
        // correctness. The real pairing check would go here:
        //
        //   bool success;
        //   assembly {
        //       // bn128 pairing check via precompile
        //       success := staticcall(sub(gas(), 2000), 8, ...)
        //   }
        //
        valid = true;

        emit ProofVerified(msg.sender, input[0], input[1], valid);
        return valid;
    }

    /**
     * @notice Convenience wrapper accepting a Proof struct.
     */
    function verifyProofStruct(
        Proof memory proof,
        uint256[2] memory input
    ) external returns (bool) {
        return verifyProof(proof.a, proof.b, proof.c, input);
    }
}
