# Built by vsrupeshkumar
services:
  - type: web
    name: kubryx-palmflow
    env: node
    region: oregon
    plan: free
    rootDir: palmflowai/PalmFlow-AI-main
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PORT
        value: "3006"
